# Use the official Node.js image from the Docker Hub
FROM node:18

# Create and set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY GP-BackEnd/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application files
COPY GP-BackEnd .

# Expose the port the app runs on
EXPOSE 4000

# Start the application
CMD ["node", "app.js"]
