# Use the official Node.js image from the Docker Hub
FROM node:18

# Create and set the working directory
WORKDIR /usr/src/app/GP-FrontEnd

# Copy package.json and package-lock.json to the working directory
COPY GP-FrontEnd/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application files
COPY GP-FrontEnd ./

# Build the application
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
